<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB as DB;
use Illuminate\Support\Facades\Schema as Schema;

class CountryTableSeeder extends Seeder
{
    public function run()
    {
        // Collection name
        $collection = 'countries';

        // Removing existing collection
        Schema::drop($collection);

        // Creating a collection schema with required index fields
        Schema::create($collection, function ($collection) {
            $collection->unique('iso3');
        });

        DB::collection($collection)->insert(['country_code' => 'AD', 'name' => 'ANDORRA', 'country_name' => 'Andorra', 'iso3' => 'AND', 'numcode' => 20, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AF', 'name' => 'AFGHANISTAN', 'country_name' => 'Afghanistan', 'iso3' => 'AFG', 'numcode' => 4, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AG', 'name' => 'ANTIGUA AND BARBUDA', 'country_name' => 'Antigua and Barbuda', 'iso3' => 'ATG', 'numcode' => 28, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AI', 'name' => 'ANGUILLA', 'country_name' => 'Anguilla', 'iso3' => 'AIA', 'numcode' => 660, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AL', 'name' => 'ALBANIA', 'country_name' => 'Albania', 'iso3' => 'ALB', 'numcode' => 8, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AM', 'name' => 'ARMENIA', 'country_name' => 'Armenia', 'iso3' => 'ARM', 'numcode' => 51, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AN', 'name' => 'NETHERLANDS ANTILLES', 'country_name' => 'Netherlands Antilles', 'iso3' => 'ANT', 'numcode' => 530, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AO', 'name' => 'ANGOLA', 'country_name' => 'Angola', 'iso3' => 'AGO', 'numcode' => 24, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AT', 'name' => 'AUSTRIA', 'country_name' => 'Austria', 'iso3' => 'AUT', 'numcode' => 40, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AU', 'name' => 'AUSTRALIA', 'country_name' => 'Australia', 'iso3' => 'AUS', 'numcode' => 36, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AZ', 'name' => 'AZERBAIJAN', 'country_name' => 'Azerbaijan', 'iso3' => 'AZE', 'numcode' => 31, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BA', 'name' => 'BOSNIA AND HERZEGOVINA', 'country_name' => 'Bosnia and Herzegovina', 'iso3' => 'BIH', 'numcode' => 70, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BB', 'name' => 'BARBADOS', 'country_name' => 'Barbados', 'iso3' => 'BRB', 'numcode' => 52, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BD', 'name' => 'BANGLADESH', 'country_name' => 'Bangladesh', 'iso3' => 'BGD', 'numcode' => 50, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BE', 'name' => 'BELGIUM', 'country_name' => 'Belgium', 'iso3' => 'BEL', 'numcode' => 56, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BF', 'name' => 'BURKINA FASO', 'country_name' => 'Burkina Faso', 'iso3' => 'BFA', 'numcode' => 854, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BG', 'name' => 'BULGARIA', 'country_name' => 'Bulgaria', 'iso3' => 'BGR', 'numcode' => 100, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BH', 'name' => 'BAHRAIN', 'country_name' => 'Bahrain', 'iso3' => 'BHR', 'numcode' => 48, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BI', 'name' => 'BURUNDI', 'country_name' => 'Burundi', 'iso3' => 'BDI', 'numcode' => 108, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BM', 'name' => 'BERMUDA', 'country_name' => 'Bermuda', 'iso3' => 'BMU', 'numcode' => 60, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BN', 'name' => 'BRUNEI DARUSSALAM', 'country_name' => 'Brunei Darussalam', 'iso3' => 'BRN', 'numcode' => 96, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BO', 'name' => 'BOLIVIA', 'country_name' => 'Bolivia', 'iso3' => 'BOL', 'numcode' => 68, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BT', 'name' => 'BHUTAN', 'country_name' => 'Bhutan', 'iso3' => 'BTN', 'numcode' => 64, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BV', 'name' => 'BOUVET ISLAND', 'country_name' => 'Bouvet Island', 'iso3' => 'BVT', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'BW', 'name' => 'BOTSWANA', 'country_name' => 'Botswana', 'iso3' => 'BWA', 'numcode' => 72, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BY', 'name' => 'BELARUS', 'country_name' => 'Belarus', 'iso3' => 'BLR', 'numcode' => 112, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BZ', 'name' => 'BELIZE', 'country_name' => 'Belize', 'iso3' => 'BLZ', 'numcode' => 84, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CC', 'name' => 'COCOS (KEELING) ISLANDS', 'country_name' => 'Cocos (Keeling) Islands', 'iso3' => 'CCK', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'CD', 'name' => 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', 'country_name' => 'Congo, the Democratic Republic of the', 'iso3' => 'COD', 'numcode' => 180, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CF', 'name' => 'CENTRAL AFRICAN REPUBLIC', 'country_name' => 'Central African Republic', 'iso3' => 'CAF', 'numcode' => 140, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CI', 'name' => 'COTE D"IVOIRE', 'country_name' => 'Cote D"Ivoire', 'iso3' => 'CIV', 'numcode' => 384, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CK', 'name' => 'COOK ISLANDS', 'country_name' => 'Cook Islands', 'iso3' => 'COK', 'numcode' => 184, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CM', 'name' => 'CAMEROON', 'country_name' => 'Cameroon', 'iso3' => 'CMR', 'numcode' => 120, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CR', 'name' => 'COSTA RICA', 'country_name' => 'Costa Rica', 'iso3' => 'CRI', 'numcode' => 188, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CV', 'name' => 'CAPE VERDE', 'country_name' => 'Cape Verde', 'iso3' => 'CPV', 'numcode' => 132, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CX', 'name' => 'CHRISTMAS ISLAND', 'country_name' => 'Christmas Island', 'iso3' => 'CXR', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'CY', 'name' => 'CYPRUS', 'country_name' => 'Cyprus', 'iso3' => 'CYP', 'numcode' => 196, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'DE', 'name' => 'GERMANY', 'country_name' => 'Germany', 'iso3' => 'DEU', 'numcode' => 276, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'DJ', 'name' => 'DJIBOUTI', 'country_name' => 'Djibouti', 'iso3' => 'DJI', 'numcode' => 262, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'DM', 'name' => 'DOMINICA', 'country_name' => 'Dominica', 'iso3' => 'DMA', 'numcode' => 212, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'DO', 'name' => 'DOMINICAN REPUBLIC', 'country_name' => 'Dominican Republic', 'iso3' => 'DOM', 'numcode' => 214, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'DZ', 'name' => 'ALGERIA', 'country_name' => 'Algeria', 'iso3' => 'DZA', 'numcode' => 12, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'EC', 'name' => 'ECUADOR', 'country_name' => 'Ecuador', 'iso3' => 'ECU', 'numcode' => 218, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'EE', 'name' => 'ESTONIA', 'country_name' => 'Estonia', 'iso3' => 'EST', 'numcode' => 233, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'EH', 'name' => 'WESTERN SAHARA', 'country_name' => 'Western Sahara', 'iso3' => 'ESH', 'numcode' => 732, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ER', 'name' => 'ERITREA', 'country_name' => 'Eritrea', 'iso3' => 'ERI', 'numcode' => 232, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ET', 'name' => 'ETHIOPIA', 'country_name' => 'Ethiopia', 'iso3' => 'ETH', 'numcode' => 231, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'FI', 'name' => 'FINLAND', 'country_name' => 'Finland', 'iso3' => 'FIN', 'numcode' => 246, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'FK', 'name' => 'FALKLAND ISLANDS (MALVINAS)', 'country_name' => 'Falkland Islands (Malvinas)', 'iso3' => 'FLK', 'numcode' => 238, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'FM', 'name' => 'MICRONESIA, FEDERATED STATES OF', 'country_name' => 'Micronesia, Federated States of', 'iso3' => 'FSM', 'numcode' => 583, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'FO', 'name' => 'FAROE ISLANDS', 'country_name' => 'Faroe Islands', 'iso3' => 'FRO', 'numcode' => 234, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'FR', 'name' => 'FRANCE', 'country_name' => 'France', 'iso3' => 'FRA', 'numcode' => 250, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GD', 'name' => 'GRENADA', 'country_name' => 'Grenada', 'iso3' => 'GRD', 'numcode' => 308, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GE', 'name' => 'GEORGIA', 'country_name' => 'Georgia', 'iso3' => 'GEO', 'numcode' => 268, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GF', 'name' => 'FRENCH GUIANA', 'country_name' => 'French Guiana', 'iso3' => 'GUF', 'numcode' => 254, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GI', 'name' => 'GIBRALTAR', 'country_name' => 'Gibraltar', 'iso3' => 'GIB', 'numcode' => 292, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GL', 'name' => 'GREENLAND', 'country_name' => 'Greenland', 'iso3' => 'GRL', 'numcode' => 304, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GM', 'name' => 'GAMBIA', 'country_name' => 'Gambia', 'iso3' => 'GMB', 'numcode' => 270, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GN', 'name' => 'GUINEA', 'country_name' => 'Guinea', 'iso3' => 'GIN', 'numcode' => 324, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GP', 'name' => 'GUADELOUPE', 'country_name' => 'Guadeloupe', 'iso3' => 'GLP', 'numcode' => 312, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GQ', 'name' => 'EQUATORIAL GUINEA', 'country_name' => 'Equatorial Guinea', 'iso3' => 'GNQ', 'numcode' => 226, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GR', 'name' => 'GREECE', 'country_name' => 'Greece', 'iso3' => 'GRC', 'numcode' => 300, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GT', 'name' => 'GUATEMALA', 'country_name' => 'Guatemala', 'iso3' => 'GTM', 'numcode' => 320, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GW', 'name' => 'GUINEA-BISSAU', 'country_name' => 'Guinea-Bissau', 'iso3' => 'GNB', 'numcode' => 624, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GY', 'name' => 'GUYANA', 'country_name' => 'Guyana', 'iso3' => 'GUY', 'numcode' => 328, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'HM', 'name' => 'HEARD ISLAND AND MCDONALD ISLANDS', 'country_name' => 'Heard Island and Mcdonald Islands', 'iso3' => 'HMD', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'HN', 'name' => 'HONDURAS', 'country_name' => 'Honduras', 'iso3' => 'HND', 'numcode' => 340, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'HR', 'name' => 'CROATIA', 'country_name' => 'Croatia', 'iso3' => 'HRV', 'numcode' => 191, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'HU', 'name' => 'HUNGARY', 'country_name' => 'Hungary', 'iso3' => 'HUN', 'numcode' => 348, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IE', 'name' => 'IRELAND', 'country_name' => 'Ireland', 'iso3' => 'IRL', 'numcode' => 372, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IL', 'name' => 'ISRAEL', 'country_name' => 'Israel', 'iso3' => 'ISR', 'numcode' => 376, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IO', 'name' => 'BRITISH INDIAN OCEAN TERRITORY', 'country_name' => 'British Indian Ocean Territory', 'iso3' => 'IOT', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'IR', 'name' => 'IRAN, ISLAMIC REPUBLIC OF', 'country_name' => 'Iran, Islamic Republic of', 'iso3' => 'IRN', 'numcode' => 364, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IS', 'name' => 'ICELAND', 'country_name' => 'Iceland', 'iso3' => 'ISL', 'numcode' => 352, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'JM', 'name' => 'JAMAICA', 'country_name' => 'Jamaica', 'iso3' => 'JAM', 'numcode' => 388, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'JO', 'name' => 'JORDAN', 'country_name' => 'Jordan', 'iso3' => 'JOR', 'numcode' => 400, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KG', 'name' => 'KYRGYZSTAN', 'country_name' => 'Kyrgyzstan', 'iso3' => 'KGZ', 'numcode' => 417, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KH', 'name' => 'CAMBODIA', 'country_name' => 'Cambodia', 'iso3' => 'KHM', 'numcode' => 116, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KM', 'name' => 'COMOROS', 'country_name' => 'Comoros', 'iso3' => 'COM', 'numcode' => 174, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KN', 'name' => 'SAINT KITTS AND NEVIS', 'country_name' => 'Saint Kitts and Nevis', 'iso3' => 'KNA', 'numcode' => 659, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KP', 'name' => 'KOREA, DEMOCRATIC PEOPLE"S REPUBLIC OF', 'country_name' => 'Korea, Democratic People"s Republic of', 'iso3' => 'PRK', 'numcode' => 408, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KR', 'name' => 'KOREA, REPUBLIC OF', 'country_name' => 'Korea, Republic of', 'iso3' => 'KOR', 'numcode' => 410, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KW', 'name' => 'KUWAIT', 'country_name' => 'Kuwait', 'iso3' => 'KWT', 'numcode' => 414, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KY', 'name' => 'CAYMAN ISLANDS', 'country_name' => 'Cayman Islands', 'iso3' => 'CYM', 'numcode' => 136, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KZ', 'name' => 'KAZAKHSTAN', 'country_name' => 'Kazakhstan', 'iso3' => 'KAZ', 'numcode' => 398, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LA', 'name' => 'LAO PEOPLE"S DEMOCRATIC REPUBLIC', 'country_name' => 'Lao People"s Democratic Republic', 'iso3' => 'LAO', 'numcode' => 418, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LB', 'name' => 'LEBANON', 'country_name' => 'Lebanon', 'iso3' => 'LBN', 'numcode' => 422, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LC', 'name' => 'SAINT LUCIA', 'country_name' => 'Saint Lucia', 'iso3' => 'LCA', 'numcode' => 662, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LI', 'name' => 'LIECHTENSTEIN', 'country_name' => 'Liechtenstein', 'iso3' => 'LIE', 'numcode' => 438, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LK', 'name' => 'SRI LANKA', 'country_name' => 'Sri Lanka', 'iso3' => 'LKA', 'numcode' => 144, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LR', 'name' => 'LIBERIA', 'country_name' => 'Liberia', 'iso3' => 'LBR', 'numcode' => 430, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LS', 'name' => 'LESOTHO', 'country_name' => 'Lesotho', 'iso3' => 'LSO', 'numcode' => 426, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LT', 'name' => 'LITHUANIA', 'country_name' => 'Lithuania', 'iso3' => 'LTU', 'numcode' => 440, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LU', 'name' => 'LUXEMBOURG', 'country_name' => 'Luxembourg', 'iso3' => 'LUX', 'numcode' => 442, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LV', 'name' => 'LATVIA', 'country_name' => 'Latvia', 'iso3' => 'LVA', 'numcode' => 428, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'LY', 'name' => 'LIBYAN ARAB JAMAHIRIYA', 'country_name' => 'Libyan Arab Jamahiriya', 'iso3' => 'LBY', 'numcode' => 434, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MA', 'name' => 'MOROCCO', 'country_name' => 'Morocco', 'iso3' => 'MAR', 'numcode' => 504, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MC', 'name' => 'MONACO', 'country_name' => 'Monaco', 'iso3' => 'MCO', 'numcode' => 492, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MD', 'name' => 'MOLDOVA, REPUBLIC OF', 'country_name' => 'Moldova, Republic of', 'iso3' => 'MDA', 'numcode' => 498, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MG', 'name' => 'MADAGASCAR', 'country_name' => 'Madagascar', 'iso3' => 'MDG', 'numcode' => 450, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MH', 'name' => 'MARSHALL ISLANDS', 'country_name' => 'Marshall Islands', 'iso3' => 'MHL', 'numcode' => 584, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MM', 'name' => 'MYANMAR', 'country_name' => 'Myanmar', 'iso3' => 'MMR', 'numcode' => 104, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MN', 'name' => 'MONGOLIA', 'country_name' => 'Mongolia', 'iso3' => 'MNG', 'numcode' => 496, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MP', 'name' => 'NORTHERN MARIANA ISLANDS', 'country_name' => 'Northern Mariana Islands', 'iso3' => 'MNP', 'numcode' => 580, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MQ', 'name' => 'MARTINIQUE', 'country_name' => 'Martinique', 'iso3' => 'MTQ', 'numcode' => 474, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MR', 'name' => 'MAURITANIA', 'country_name' => 'Mauritania', 'iso3' => 'MRT', 'numcode' => 478, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MS', 'name' => 'MONTSERRAT', 'country_name' => 'Montserrat', 'iso3' => 'MSR', 'numcode' => 500, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MU', 'name' => 'MAURITIUS', 'country_name' => 'Mauritius', 'iso3' => 'MUS', 'numcode' => 480, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MV', 'name' => 'MALDIVES', 'country_name' => 'Maldives', 'iso3' => 'MDV', 'numcode' => 462, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MW', 'name' => 'MALAWI', 'country_name' => 'Malawi', 'iso3' => 'MWI', 'numcode' => 454, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MX', 'name' => 'MEXICO', 'country_name' => 'Mexico', 'iso3' => 'MEX', 'numcode' => 484, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MY', 'name' => 'MALAYSIA', 'country_name' => 'Malaysia', 'iso3' => 'MYS', 'numcode' => 458, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MZ', 'name' => 'MOZAMBIQUE', 'country_name' => 'Mozambique', 'iso3' => 'MOZ', 'numcode' => 508, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NA', 'name' => 'NAMIBIA', 'country_name' => 'Namibia', 'iso3' => 'NAM', 'numcode' => 516, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NC', 'name' => 'NEW CALEDONIA', 'country_name' => 'New Caledonia', 'iso3' => 'NCL', 'numcode' => 540, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NF', 'name' => 'NORFOLK ISLAND', 'country_name' => 'Norfolk Island', 'iso3' => 'NFK', 'numcode' => 574, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NG', 'name' => 'NIGERIA', 'country_name' => 'Nigeria', 'iso3' => 'NGA', 'numcode' => 566, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NI', 'name' => 'NICARAGUA', 'country_name' => 'Nicaragua', 'iso3' => 'NIC', 'numcode' => 558, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NL', 'name' => 'NETHERLANDS', 'country_name' => 'Netherlands', 'iso3' => 'NLD', 'numcode' => 528, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NO', 'name' => 'NORWAY', 'country_name' => 'Norway', 'iso3' => 'NOR', 'numcode' => 578, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PA', 'name' => 'PANAMA', 'country_name' => 'Panama', 'iso3' => 'PAN', 'numcode' => 591, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PF', 'name' => 'FRENCH POLYNESIA', 'country_name' => 'French Polynesia', 'iso3' => 'PYF', 'numcode' => 258, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PG', 'name' => 'PAPUA NEW GUINEA', 'country_name' => 'Papua New Guinea', 'iso3' => 'PNG', 'numcode' => 598, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PH', 'name' => 'PHILIPPINES', 'country_name' => 'Philippines', 'iso3' => 'PHL', 'numcode' => 608, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PK', 'name' => 'PAKISTAN', 'country_name' => 'Pakistan', 'iso3' => 'PAK', 'numcode' => 586, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PL', 'name' => 'POLAND', 'country_name' => 'Poland', 'iso3' => 'POL', 'numcode' => 616, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PM', 'name' => 'SAINT PIERRE AND MIQUELON', 'country_name' => 'Saint Pierre and Miquelon', 'iso3' => 'SPM', 'numcode' => 666, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PN', 'name' => 'PITCAIRN', 'country_name' => 'Pitcairn', 'iso3' => 'PCN', 'numcode' => 612, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PR', 'name' => 'PUERTO RICO', 'country_name' => 'Puerto Rico', 'iso3' => 'PRI', 'numcode' => 630, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PS', 'name' => 'PALESTINIAN TERRITORY, OCCUPIED', 'country_name' => 'Palestinian Territory, Occupied', 'iso3' => 'PSE', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'PT', 'name' => 'PORTUGAL', 'country_name' => 'Portugal', 'iso3' => 'PRT', 'numcode' => 620, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PY', 'name' => 'PARAGUAY', 'country_name' => 'Paraguay', 'iso3' => 'PRY', 'numcode' => 600, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'RE', 'name' => 'REUNION', 'country_name' => 'Reunion', 'iso3' => 'REU', 'numcode' => 638, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'RO', 'name' => 'ROMANIA', 'country_name' => 'Romania', 'iso3' => 'ROM', 'numcode' => 642, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'RW', 'name' => 'RWANDA', 'country_name' => 'Rwanda', 'iso3' => 'RWA', 'numcode' => 646, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SA', 'name' => 'SAUDI ARABIA', 'country_name' => 'Saudi Arabia', 'iso3' => 'SAU', 'numcode' => 682, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SB', 'name' => 'SOLOMON ISLANDS', 'country_name' => 'Solomon Islands', 'iso3' => 'SLB', 'numcode' => 90, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SC', 'name' => 'SEYCHELLES', 'country_name' => 'Seychelles', 'iso3' => 'SYC', 'numcode' => 690, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SE', 'name' => 'SWEDEN', 'country_name' => 'Sweden', 'iso3' => 'SWE', 'numcode' => 752, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SH', 'name' => 'SAINT HELENA', 'country_name' => 'Saint Helena', 'iso3' => 'SHN', 'numcode' => 654, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SI', 'name' => 'SLOVENIA', 'country_name' => 'Slovenia', 'iso3' => 'SVN', 'numcode' => 705, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SJ', 'name' => 'SVALBARD AND JAN MAYEN', 'country_name' => 'Svalbard and Jan Mayen', 'iso3' => 'SJM', 'numcode' => 744, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SK', 'name' => 'SLOVAKIA', 'country_name' => 'Slovakia', 'iso3' => 'SVK', 'numcode' => 703, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SL', 'name' => 'SIERRA LEONE', 'country_name' => 'Sierra Leone', 'iso3' => 'SLE', 'numcode' => 694, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SM', 'name' => 'SAN MARINO', 'country_name' => 'San Marino', 'iso3' => 'SMR', 'numcode' => 674, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SN', 'name' => 'SENEGAL', 'country_name' => 'Senegal', 'iso3' => 'SEN', 'numcode' => 686, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SO', 'name' => 'SOMALIA', 'country_name' => 'Somalia', 'iso3' => 'SOM', 'numcode' => 706, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SR', 'name' => 'SURINAME', 'country_name' => 'Suriname', 'iso3' => 'SUR', 'numcode' => 740, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ST', 'name' => 'SAO TOME AND PRINCIPE', 'country_name' => 'Sao Tome and Principe', 'iso3' => 'STP', 'numcode' => 678, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SV', 'name' => 'EL SALVADOR', 'country_name' => 'El Salvador', 'iso3' => 'SLV', 'numcode' => 222, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SY', 'name' => 'SYRIAN ARAB REPUBLIC', 'country_name' => 'Syrian Arab Republic', 'iso3' => 'SYR', 'numcode' => 760, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SZ', 'name' => 'SWAZILAND', 'country_name' => 'Swaziland', 'iso3' => 'SWZ', 'numcode' => 748, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TC', 'name' => 'TURKS AND CAICOS ISLANDS', 'country_name' => 'Turks and Caicos Islands', 'iso3' => 'TCA', 'numcode' => 796, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TF', 'name' => 'FRENCH SOUTHERN TERRITORIES', 'country_name' => 'French Southern Territories', 'iso3' => 'ATF', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'TH', 'name' => 'THAILAND', 'country_name' => 'Thailand', 'iso3' => 'THA', 'numcode' => 764, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TJ', 'name' => 'TAJIKISTAN', 'country_name' => 'Tajikistan', 'iso3' => 'TJK', 'numcode' => 762, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TK', 'name' => 'TOKELAU', 'country_name' => 'Tokelau', 'iso3' => 'TKL', 'numcode' => 772, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TM', 'name' => 'TURKMENISTAN', 'country_name' => 'Turkmenistan', 'iso3' => 'TKM', 'numcode' => 795, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TN', 'name' => 'TUNISIA', 'country_name' => 'Tunisia', 'iso3' => 'TUN', 'numcode' => 788, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TR', 'name' => 'TURKEY', 'country_name' => 'Turkey', 'iso3' => 'TUR', 'numcode' => 792, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TT', 'name' => 'TRINIDAD AND TOBAGO', 'country_name' => 'Trinidad and Tobago', 'iso3' => 'TTO', 'numcode' => 780, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TV', 'name' => 'TUVALU', 'country_name' => 'Tuvalu', 'iso3' => 'TUV', 'numcode' => 798, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TZ', 'name' => 'TANZANIA, UNITED REPUBLIC OF', 'country_name' => 'Tanzania, United Republic of', 'iso3' => 'TZA', 'numcode' => 834, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'UA', 'name' => 'UKRAINE', 'country_name' => 'Ukraine', 'iso3' => 'UKR', 'numcode' => 804, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'UG', 'name' => 'UGANDA', 'country_name' => 'Uganda', 'iso3' => 'UGA', 'numcode' => 800, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'UY', 'name' => 'URUGUAY', 'country_name' => 'Uruguay', 'iso3' => 'URY', 'numcode' => 858, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'UZ', 'name' => 'UZBEKISTAN', 'country_name' => 'Uzbekistan', 'iso3' => 'UZB', 'numcode' => 860, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VA', 'name' => 'HOLY SEE (VATICAN CITY STATE)', 'country_name' => 'Holy See (Vatican City State)', 'iso3' => 'VAT', 'numcode' => 336, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VC', 'name' => 'SAINT VINCENT AND THE GRENADINES', 'country_name' => 'Saint Vincent and the Grenadines', 'iso3' => 'VCT', 'numcode' => 670, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VE', 'name' => 'VENEZUELA', 'country_name' => 'Venezuela', 'iso3' => 'VEN', 'numcode' => 862, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VG', 'name' => 'VIRGIN ISLANDS, BRITISH', 'country_name' => 'Virgin Islands, British', 'iso3' => 'VGB', 'numcode' => 92, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VI', 'name' => 'VIRGIN ISLANDS, U.S.', 'country_name' => 'Virgin Islands, U.s.', 'iso3' => 'VIR', 'numcode' => 850, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VN', 'name' => 'VIET NAM', 'country_name' => 'Viet Nam', 'iso3' => 'VNM', 'numcode' => 704, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'VU', 'name' => 'VANUATU', 'country_name' => 'Vanuatu', 'iso3' => 'VUT', 'numcode' => 548, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'WF', 'name' => 'WALLIS AND FUTUNA', 'country_name' => 'Wallis and Futuna', 'iso3' => 'WLF', 'numcode' => 876, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ZA', 'name' => 'SOUTH AFRICA', 'country_name' => 'South Africa', 'iso3' => 'ZAF', 'numcode' => 710, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ZM', 'name' => 'ZAMBIA', 'country_name' => 'Zambia', 'iso3' => 'ZMB', 'numcode' => 894, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ZW', 'name' => 'ZIMBABWE', 'country_name' => 'Zimbabwe', 'iso3' => 'ZWE', 'numcode' => 716, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AQ', 'name' => 'ANTARCTICA', 'country_name' => 'Antarctica', 'iso3' => 'ATA', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'TL', 'name' => 'TIMOR-LESTE', 'country_name' => 'Timor-Leste', 'iso3' => 'TLS', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'YT', 'name' => 'MAYOTTE', 'country_name' => 'Mayotte', 'iso3' => 'MYT', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'AE', 'name' => 'UNITED ARAB EMIRATES', 'country_name' => 'United Arab Emirates', 'iso3' => 'ARE', 'numcode' => 784, 'currency_code' => 'AED', 'currency_name' => 'United Arab Emirates Dirham', 'currency_symbol' => 'Ø¥', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CZ', 'name' => 'CZECH REPUBLIC', 'country_name' => 'Czech Republic', 'iso3' => 'CZE', 'numcode' => 203, 'currency_code' => 'CZK', 'currency_name' => 'Czech Koruna', 'currency_symbol' => 'Ä', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GB', 'name' => 'UNITED KINGDOM', 'country_name' => 'United Kingdom', 'iso3' => 'GBR', 'numcode' => 826, 'currency_code' => 'GBP', 'currency_name' => 'British Pound', 'currency_symbol' => 'Â£', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NZ', 'name' => 'NEW ZEALAND', 'country_name' => 'New Zealand', 'iso3' => 'NZL', 'numcode' => 517327, 'currency_code' => 'NZD', 'currency_name' => 'New Zealand Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'RU', 'name' => 'RUSSIAN FEDERATION', 'country_name' => 'Russian Federation', 'iso3' => 'RUS', 'numcode' => 643, 'currency_code' => 'RUB', 'currency_name' => 'Russian Rouble', 'currency_symbol' => 'Ð±', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TW', 'name' => 'TAIWAN, PROVINCE OF CHINA', 'country_name' => 'Taiwan, Province of China', 'iso3' => 'TWN', 'numcode' => 158, 'currency_code' => 'TWD', 'currency_name' => 'Taiwan Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IN', 'name' => 'INDIA', 'country_name' => 'India', 'iso3' => 'IND', 'numcode' => 356, 'currency_name' => 'Rupee', 'currency_symbol' => '&#x20b9;', 'status' => 'ACTIVE', 'default' => 'YES', 'currency_code' => 'INR',]);
        DB::collection($collection)->insert(['country_code' => 'BJ', 'name' => 'BENIN', 'country_name' => 'Benin', 'iso3' => 'BEN', 'numcode' => 204, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CG', 'name' => 'CONGO', 'country_name' => 'Congo', 'iso3' => 'COG', 'numcode' => 178, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CU', 'name' => 'CUBA', 'country_name' => 'Cuba', 'iso3' => 'CUB', 'numcode' => 192, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'EG', 'name' => 'EGYPT', 'country_name' => 'Egypt', 'iso3' => 'EGY', 'numcode' => 818, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ES', 'name' => 'SPAIN', 'country_name' => 'Spain', 'iso3' => 'ESP', 'numcode' => 724, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'FJ', 'name' => 'FIJI', 'country_name' => 'Fiji', 'iso3' => 'FJI', 'numcode' => 242, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GA', 'name' => 'GABON', 'country_name' => 'Gabon', 'iso3' => 'GAB', 'numcode' => 266, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GH', 'name' => 'GHANA', 'country_name' => 'Ghana', 'iso3' => 'GHA', 'numcode' => 288, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GU', 'name' => 'GUAM', 'country_name' => 'Guam', 'iso3' => 'GUM', 'numcode' => 316, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'HT', 'name' => 'HAITI', 'country_name' => 'Haiti', 'iso3' => 'HTI', 'numcode' => 332, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IQ', 'name' => 'IRAQ', 'country_name' => 'Iraq', 'iso3' => 'IRQ', 'numcode' => 368, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'IT', 'name' => 'ITALY', 'country_name' => 'Italy', 'iso3' => 'ITA', 'numcode' => 380, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'JP', 'name' => 'JAPAN', 'country_name' => 'Japan', 'iso3' => 'JPN', 'numcode' => 392, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KE', 'name' => 'KENYA', 'country_name' => 'Kenya', 'iso3' => 'KEN', 'numcode' => 404, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MO', 'name' => 'MACAO', 'country_name' => 'Macao', 'iso3' => 'MAC', 'numcode' => 446, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ML', 'name' => 'MALI', 'country_name' => 'Mali', 'iso3' => 'MLI', 'numcode' => 466, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MT', 'name' => 'MALTA', 'country_name' => 'Malta', 'iso3' => 'MLT', 'numcode' => 470, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NE', 'name' => 'NIGER', 'country_name' => 'Niger', 'iso3' => 'NER', 'numcode' => 562, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NU', 'name' => 'NIUE', 'country_name' => 'Niue', 'iso3' => 'NIU', 'numcode' => 570, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NP', 'name' => 'NEPAL', 'country_name' => 'Nepal', 'iso3' => 'NPL', 'numcode' => 524, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'NR', 'name' => 'NAURU', 'country_name' => 'Nauru', 'iso3' => 'NRU', 'numcode' => 520, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'OM', 'name' => 'OMAN', 'country_name' => 'Oman', 'iso3' => 'OMN', 'numcode' => 512, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PE', 'name' => 'PERU', 'country_name' => 'Peru', 'iso3' => 'PER', 'numcode' => 604, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'PW', 'name' => 'PALAU', 'country_name' => 'Palau', 'iso3' => 'PLW', 'numcode' => 585, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'QA', 'name' => 'QATAR', 'country_name' => 'Qatar', 'iso3' => 'QAT', 'numcode' => 634, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SD', 'name' => 'SUDAN', 'country_name' => 'Sudan', 'iso3' => 'SDN', 'numcode' => 736, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TD', 'name' => 'CHAD', 'country_name' => 'Chad', 'iso3' => 'TCD', 'numcode' => 148, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TG', 'name' => 'TOGO', 'country_name' => 'Togo', 'iso3' => 'TGO', 'numcode' => 768, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'TO', 'name' => 'TONGA', 'country_name' => 'Tonga', 'iso3' => 'TON', 'numcode' => 776, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'WS', 'name' => 'SAMOA', 'country_name' => 'Samoa', 'iso3' => 'WSM', 'numcode' => 882, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'YE', 'name' => 'YEMEN', 'country_name' => 'Yemen', 'iso3' => 'YEM', 'numcode' => 887, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AW', 'name' => 'ARUBA', 'country_name' => 'Aruba', 'iso3' => 'ABW', 'numcode' => 533, 'currency_code' => 'ANG', 'currency_name' => 'NL Antillian Guilder', 'currency_symbol' => 'Æ’', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AR', 'name' => 'ARGENTINA', 'country_name' => 'Argentina', 'iso3' => 'ARG', 'numcode' => 32, 'currency_code' => 'ARS', 'currency_name' => 'Argentine Peso', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'AS', 'name' => 'AMERICAN SAMOA', 'country_name' => 'American Samoa', 'iso3' => 'ASM', 'numcode' => 16, 'currency_code' => 'EUR', 'currency_name' => 'Euro', 'currency_symbol' => 'â‚¬', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BS', 'name' => 'BAHAMAS', 'country_name' => 'Bahamas', 'iso3' => 'BHS', 'numcode' => 44, 'currency_code' => 'BSD', 'currency_name' => 'Bahamian Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'BR', 'name' => 'BRAZIL', 'country_name' => 'Brazil', 'iso3' => 'BRA', 'numcode' => 76, 'currency_code' => 'BRL', 'currency_name' => 'Brazilian Real', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CA', 'name' => 'CANADA', 'country_name' => 'Canada', 'iso3' => 'CAN', 'numcode' => 124, 'currency_code' => 'CAD', 'currency_name' => 'Canadian Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CH', 'name' => 'SWITZERLAND', 'country_name' => 'Switzerland', 'iso3' => 'CHE', 'numcode' => 756, 'currency_code' => 'CHF', 'currency_name' => 'Swiss Franc', 'currency_symbol' => 'F', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CL', 'name' => 'CHILE', 'country_name' => 'Chile', 'iso3' => 'CHL', 'numcode' => 152, 'currency_code' => 'CLP', 'currency_name' => 'Chilean Peso', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CN', 'name' => 'CHINA', 'country_name' => 'China', 'iso3' => 'CHN', 'numcode' => 156, 'currency_code' => 'CNY', 'currency_name' => 'Chinese Yuan Renminbi', 'currency_symbol' => 'Â¥', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'CO', 'name' => 'COLOMBIA', 'country_name' => 'Colombia', 'iso3' => 'COL', 'numcode' => 170, 'currency_code' => 'COP', 'currency_name' => 'Colombian Peso', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'DK', 'name' => 'DENMARK', 'country_name' => 'Denmark', 'iso3' => 'DNK', 'numcode' => 208, 'currency_code' => 'DKK', 'currency_name' => 'Danish Krone', 'currency_symbol' => 'r', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'HK', 'name' => 'HONG KONG', 'country_name' => 'Hong Kong', 'iso3' => 'HKG', 'numcode' => 344, 'currency_code' => 'HKD', 'currency_name' => 'Hong Kong Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'ID', 'name' => 'INDONESIA', 'country_name' => 'Indonesia', 'iso3' => 'IDN', 'numcode' => 360, 'currency_code' => 'IDR', 'currency_name' => 'Indonesian Rupiah', 'currency_symbol' => 'p', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'KI', 'name' => 'KIRIBATI', 'country_name' => 'Kiribati', 'iso3' => 'KIR', 'numcode' => 296, 'currency_code' => 'AUD', 'currency_name' => 'Australian Dollars', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'MK', 'name' => 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', 'country_name' => 'Macedonia, the Former Yugoslav Republic of', 'iso3' => 'MKD', 'numcode' => 807, 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'SG', 'name' => 'SINGAPORE', 'country_name' => 'Singapore', 'iso3' => 'SGP', 'numcode' => 702, 'currency_code' => 'SGD', 'currency_name' => 'Singapore Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);
        DB::collection($collection)->insert(['country_code' => 'GS', 'name' => 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', 'country_name' => 'South Georgia and the South Sandwich Islands', 'iso3' => 'SGS', 'numcode' => '', 'default' => 'NO', 'status' => 'INACTIVE',]);
        DB::collection($collection)->insert(['country_code' => 'US', 'name' => 'UNITED STATES', 'country_name' => 'United States', 'iso3' => 'USA', 'numcode' => 840, 'currency_code' => 'USD', 'currency_name' => 'US Dollar', 'currency_symbol' => '$', 'status' => 'INACTIVE', 'default' => 'NO',]);


    }
}
